Fixed inconsistent `_pick_locations` return values for 0 locations  (#610)
* Error calling the _match_voxel_intersection method

Sometimes running the voxel_intersection strategy (e.g. connecting Golgi cells by means of gap junctions) yields the following error
```  
File "/home/alessio/Documenti/GitHub/bsb/bsb/connectivity/detailed/voxel_intersection.py", line 116, in _match_voxel_intersection
    tlocs[s:e] = tblock
ValueError: could not broadcast input array from shape (0,) into shape (0,3)
````
I found that this error happens when tblock is an empty list, which is due to the fact that sometimes the _pick_locations method called at line 100 of voxel_intersection.py returns ([ ],[ ]). Checking if the output of _pick_locations called at line 100 is not ([ ],[ ]) in order to decide whether to append it to data_acc or not (original line 103) solves the problem.

* Reformatted voxel_intersection with black

* changed location of fix

* warn if there's no roi

* fixed voxel picking, but morphology labels are displeased

* fixed swapped target/candidate picks

Co-authored-by: Robin De Schepper <robin.deschepper93@gmail.com>